# This is a basic workflow to help you get started with Actions
name: build-mcp-time

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: src/03-mcp-servers

env:
  APP_NAME: mcp-customers

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        docker build . --file Dockerfile-customers --tag $APP_NAME --label "runnumber=${GITHUB_RUN_ID}"

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        APP_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/mcp-servers/$APP_NAME
        docker tag $APP_NAME $APP_IMAGE_ID:${GITHUB_RUN_ID}
        docker tag $APP_NAME $APP_IMAGE_ID:latest
        docker push $APP_IMAGE_ID:${GITHUB_RUN_ID}
        docker push $APP_IMAGE_ID:latest
